Implementation of first task
believerfenix/firtst_task_yalantis pull request #1
Opened 2021-08-22 15:42 UTC by believerfenix

2021-08-22 19:13 UTC, EvgeniiKhudan requested changes
Подумайте еще раз, что может быть в консантах, а что не должно.
Попробуйте улучшить ваш алгоритм поиска.
Сделайте более тестируемый интерфейс добавление транспорта в автопарк.
Вы принимаете слишком много аргументов в ваши инициализаторы объектов, скорее всего вам не нужно переопределять то, что вы берете из констант

2021-08-22 19:13 UTC, EvgeniiKhudan commented on source/car.rb
> +  def initialize(max_weight, speed, available)
зачем вы разрешаете передавать аргументы, если потом их не используете?

2021-08-22 19:13 UTC, EvgeniiKhudan commented on source/car.rb
> +  def create_registration_number
у вас все машины с одинаковым регистрационным номером? Сделайте это аргументом или делайте его рандомным

2021-08-22 19:13 UTC, EvgeniiKhudan commented on source/delivery_service.rb
> +  def create_delivery_park
Этот метод практически невозможно тестировать. Попробуйте сделать удобный интерфейс добавления транспорта по одному. Так у вас будет больше контроля, сколько и чего вы добавили и в каком они статусе.

2021-08-22 19:13 UTC, EvgeniiKhudan commented on source/delivery_service.rb
> +    if delivery_distance <= Constant::BIKE_MAX_DISTANCE && delivery_weight <= Constant::BIKE_MAX_WEIGHT
Попробуйте реализовать механизма транспорта не делая зависимостей на конкретике, но на абстракциях. Почему должен выпасть выбор на bike? чтобы не везти на грузовике конверт с документами в соседний подъезд. В идеале при добавлении новых видов транспорта у вас не должно быть необходимости менять алгоритм.

2021-08-22 19:13 UTC, EvgeniiKhudan commented on source/transport.rb
> +    delivery_efficiency <=> other.delivery_efficiency
Попробуйте поиграться с return 1/0/-1. Так вы лучше поймете, как работает Comparable под капотом.

2021-08-22 19:13 UTC, EvgeniiKhudan commented on source/delivery_service.rb
> +      puts 'Sorry! We cannot deliver it'
Подумайте, что должен вернуть ваш метод при неуспешном сценарии. Вывод на консоль не вариант

2021-08-22 19:19 UTC, EvgeniiKhudan requested changes

2021-08-22 19:19 UTC, EvgeniiKhudan commented on module/validation_availability.rb
> +module ValidationAvailability
Ваш модуль завязан на конкретики и имеет совсем непонятное назначение. Availability это просто свойство каждого объекта типа транспорт, на этом и остановитесь

2021-08-22 19:19 UTC, EvgeniiKhudan commented on source/bike.rb
> +  attr_reader :max_distance
подумайте, возможно вы хотите дать доступ еще и к speed, available.

2021-08-31 23:09 UTC, believerfenix commented on module/validation_availability.rb
> +    puts 'Sorry! We have no free transport'
при корректной отработке возвращает подходящий транспорт. При ошибке добавил raise

2021-08-31 23:09 UTC, believerfenix commented on source/bike.rb
> +  attr_reader :max_distance
добавил эти атрибуты в класс transport

2021-08-31 23:09 UTC, believerfenix commented on source/car.rb
> +  def initialize(max_weight, speed, available)
неправильно реализовал классы. Аргументы убрал

2021-08-31 23:09 UTC, believerfenix commented on source/car.rb
> +  def create_registration_number
сделал случайными

2021-08-31 23:09 UTC, believerfenix commented on source/delivery_service.rb
> +  def create_delivery_park
Поменял

2021-08-31 23:09 UTC, believerfenix commented on source/delivery_service.rb
> +    if delivery_distance <= Constant::BIKE_MAX_DISTANCE && delivery_weight <= Constant::BIKE_MAX_WEIGHT
Реализовал подбор транспорта через сортировку и фильтрацию в соответствии с новым дз

2021-08-31 23:09 UTC, believerfenix commented on source/delivery_service.rb
> +      puts 'Sorry! We cannot deliver it'
поменял на raise

2021-08-31 23:11 UTC, believerfenix commented
> Подумайте еще раз, что может быть в консантах, а что не должно.
> Попробуйте улучшить ваш алгоритм поиска.
> Сделайте более тестируемый интерфейс добавление транспорта в автопарк.
> Вы принимаете слишком много аргументов в ваши инициализаторы объектов, скорее всего вам не нужно переопределять то, что вы берете из констант

2021-08-31 23:22 UTC, believerfenix commented on source/bike.rb
> +  attr_reader :max_distance
Не могу запросить повторное ревью, можете, пожалуйста, посмотреть изменения

2021-08-31 23:26 UTC, believerfenix commented
Не могу запросить повторное ревью, посмотрите изменения, пожалуйста

2021-08-31 23:26 UTC, believerfenix commented
Также добавил еще один пул реквест с законченным 2 заданием

2021-09-05 15:05 UTC, merged