Implementation of second task
believerfenix/firtst_task_yalantis pull request #2
Opened 2021-08-31 23:24 UTC by believerfenix

2021-09-04 09:59 UTC, EvgeniiKhudan requested changes
оставил комментарии

2021-09-04 09:59 UTC, EvgeniiKhudan commented on spec/delivery_service_spec.rb
> +RSpec.describe DeliveryService do
Ваши тесты по факту ничего не проверяют. Вы должны воображать различные ситуации в голове и отображать это в тестах. Что если у меня пустой массив транспорта, что если там будет только один недоступный байк, что будет если будут доступные и байки и машины. Думайте о граничных значениях и как должен повести себя ваш алгоритм. 
`.not_to eq(nil)` это не проверка. Вы должны проверять, что ваш алгоритм вернул конкретный байк или машину, которую вы ожидаете увидеть результатом ваших входящих данных.
'raises error because can not delivery that' здесь хочется задать вопрос why? Вот и напишите почему, с какими входящими данными вы не найдете доступный транспорт

2021-09-04 09:59 UTC, EvgeniiKhudan commented on spec/transport_spec.rb
> +    expect([transport1, transport2, transport3, transport4, transport5, transport6].sort).to eq(sorted_transport)
сортировка должна работать от меньшего к большему, никак не наооборот. 
Представьте что вы сортируете по алфавиту а у вас люди начинаются с последней буквы Я например.

2021-09-04 09:59 UTC, EvgeniiKhudan commented on spec/transport_spec.rb
> +RSpec.describe Transport do
Не хватает тестов на <=> метод. Попробуйте сравнить транспорт, который должен быть равен между собой. < > тоже желательно протестировать

2021-09-05 15:51 UTC, believerfenix commented on spec/transport_spec.rb
> +    expect([transport1, transport2, transport3, transport4, transport5, transport6].sort).to eq(sorted_transport)
Этим тестов я проверяю  <=> метод. В первом задании было указано "сравнивать по скорости доставки 1 кг посылки"(speed / max_weight), и получается что сначала идут Car(speed = 50, max_weight = 100, коеф 0,5), а потом Bike(speed = 10, max_weight = 10, коеф 1). Если это не правильно, я исправлю, но в моем понимании задания это должно выглядеть так

2021-09-30 17:28 UTC, EvgeniiKhudan approved these changes
LGTM!

2021-09-30 17:53 UTC, merged